# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - release

cache : packages

warnings_are_errors : false
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

r_packages:
  - covr
  - devtools

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars

script:
  - R CMD build .
  - R CMD check *tar.gz



addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

after_success:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars
  - Rscript -e 'covr::package_coverage(quiet = FALSE)'
