# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - release

cache : packages

warnings_are_errors : false

#r_github_packages: 
#  - r-lib/covr

r_packages:
  - covr

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - ls
  - ls ..
  - Rscript -e 'covr::codecov(path="../NeutronNoise")'
