// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// feynman_hist
DataFrame feynman_hist(const DataFrame x, const NumericVector samples_widths, int max_nb_samples, const int verbose);
RcppExport SEXP _NeutronNoise_feynman_hist(SEXP xSEXP, SEXP samples_widthsSEXP, SEXP max_nb_samplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type samples_widths(samples_widthsSEXP);
    Rcpp::traits::input_parameter< int >::type max_nb_samples(max_nb_samplesSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(feynman_hist(x, samples_widths, max_nb_samples, verbose));
    return rcpp_result_gen;
END_RCPP
}
// feynman_v2m
DataFrame feynman_v2m(DataFrame x, NumericVector samples_widths, int max_nb_samples, int verbose);
RcppExport SEXP _NeutronNoise_feynman_v2m(SEXP xSEXP, SEXP samples_widthsSEXP, SEXP max_nb_samplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type samples_widths(samples_widthsSEXP);
    Rcpp::traits::input_parameter< int >::type max_nb_samples(max_nb_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(feynman_v2m(x, samples_widths, max_nb_samples, verbose));
    return rcpp_result_gen;
END_RCPP
}
// get_fission_chains_length
List get_fission_chains_length(int n, DataFrame fission_multiplicity, double k, int seed);
RcppExport SEXP _NeutronNoise_get_fission_chains_length(SEXP nSEXP, SEXP fission_multiplicitySEXP, SEXP kSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type fission_multiplicity(fission_multiplicitySEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_fission_chains_length(n, fission_multiplicity, k, seed));
    return rcpp_result_gen;
END_RCPP
}
// signal_shift_histories
void signal_shift_histories(NumericVector times, IntegerVector hists, double duration);
RcppExport SEXP _NeutronNoise_signal_shift_histories(SEXP timesSEXP, SEXP histsSEXP, SEXP durationSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hists(histsSEXP);
    Rcpp::traits::input_parameter< double >::type duration(durationSEXP);
    signal_shift_histories(times, hists, duration);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NeutronNoise_feynman_hist", (DL_FUNC) &_NeutronNoise_feynman_hist, 4},
    {"_NeutronNoise_feynman_v2m", (DL_FUNC) &_NeutronNoise_feynman_v2m, 4},
    {"_NeutronNoise_get_fission_chains_length", (DL_FUNC) &_NeutronNoise_get_fission_chains_length, 4},
    {"_NeutronNoise_signal_shift_histories", (DL_FUNC) &_NeutronNoise_signal_shift_histories, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_NeutronNoise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
