# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Feynman histogram
#' 
#' This function divide the signal into equal samples of width \code{T}. 
#' For each of them the number of events are counted and binned into a histogram called the Feynman histogram.
#' This histogram therefore represents the occurrence probabilities of various multiplets (i.e. 1 detection, 2 detections, etc.) occuring within
#' a specified time gate width \code{T}.
#' To avoid numerical problem with functions using \code{feynman_hist} the last sample is not taken into account.
#' 
#' @param x A sorted numeric vector representing the detection times. The function assumes that the signal starts at the time 0 seconds. 
#' @param samples_widths Numeric vector of samples width (multiple values of \code{T}).
#' @param max_nb_samples If different from 0 then the calculation is limited to the specified number of samples. 
#' @param verbose For debbuging purpose only.
#' @return A DataFrame.
#' @export
feynman_hist <- function(x, samples_widths, max_nb_samples = 0L, verbose = 0L) {
    .Call('_NeutronNoise_feynman_hist', PACKAGE = 'NeutronNoise', x, samples_widths, max_nb_samples, verbose)
}

